# Do not package for alpha & beta (for now), WoWI does not support fully.
name: Package (Release)
on:
  push:
    tags:
      - '*'
      - '!**-alpha**'
      - '!**-beta**'

jobs:
  build:
    if: github.repository_owner == 'Raenore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
